branches:
  only:
  - "/^v[0-9]/"
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-armv7
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        --env AWS_REGION=$AWS_REGION \
        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        octoblu/meshblu-connector-builder:linux-armv7 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian --destination-path=/usr/share/meshblu-connectors/configurators/meshblu-json \
            && meshblu-connector-uploader-github \
            && upload-deb-s3 \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-x86
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        --env AWS_REGION=$AWS_REGION \
        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        octoblu/meshblu-connector-builder:linux-x86 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian --destination-path=/usr/share/meshblu-connectors/configurators/meshblu-json \
            && meshblu-connector-uploader-github \
            && upload-deb-s3 \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/meshblu-connector-builder:linux-x64
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        --env AWS_REGION=$AWS_REGION \
        --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        octoblu/meshblu-connector-builder:linux-x64 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian --destination-path=/usr/share/meshblu-connectors/configurators/meshblu-json \
            && meshblu-connector-uploader-github \
            && upload-deb-s3 \
          '
  - os: osx
    node_js: '8'
    language: node_js
    after_success:
    - yarn global add meshblu-connector-pkger meshblu-connector-installer-macos meshblu-connector-uploader-github
    - |
      meshblu-connector-pkger \
      && meshblu-connector-installer-macos --destination-path=/Library/MeshbluConnectors/configurators/meshblu-json \
      && meshblu-connector-uploader-github
env:
  global:
  - secure: kT3nk8aAC6ikzgAfBaHHpOBXtWb1irWLQ16QTeKO1G6Mgu2AuvlmGOV26W2b3pdDz5enh+EjFjmPTS59cI8Q5BgC7gjGipVIU2wtRwY+dajG81uUkh8H9Y4AplFm9HVvpnuO6/AJ0bg9OsQtbvZ438y6Jn+8oDIsolEytsJJC9llNa7kFOSwV+RHm6+gtYwNWdnOXpM4T+DhkUHdZYub5V5jIqzsuqWN0V3kL1e6tupR0ulh8DT3qqooLpVIyYecVKj6BRtOm19Xcu61DF51LjCZvyTnW4UzNg9tCLFoU+oxh9viVELESgf5enftzQVc/F4c4mrP+0C4Ea5w0u716vYEA9DWtCxxBVCBP1xvS1lYNbLcm7tSSpYhMndGoKElbweJNQYpW7qzR3O69P894fKNtRC10SiQdjYTLUzap1czpHz97NmIHbBM1t9bwY/d3+6mrSUxGlibbAGLuEtW1uCewO/1753HKOrSWqlkAPpynJfbCWUWDtLABnPWdVems7wTB/E4MOez/2fODUDA645a/TgK1MgqOo6Jp2Rma5uhI7ESICYYdshfNa+9K2WJN9APWTqAxBmC+k/DTbsbc+Vs2diCX1zvB15shmPc5zIw/dPrQsxQHxk5iu8KmgIo9wu5uE//NvxSaw9oOKXlqU565/msAob1uZiNp84/5f8=
  - secure: EIS+cUH3rP3GF/GtvALzzfehwbufWBiNB7Av0lDe0xayJV/lDvbaJIaBeNa0ZtCR8zmUgt+UvplypCJr8lrZT0QLohsqfFgI2VPQ8jsJFsIu0TWHuIyDA6VVfCq0fIPEP644uPX/X64tonjGq2+Hh4dkiunlb7cxKA6yw+u2RXtE5Q1OF4UJyQ+Adf76Cmvk4tLz1Odoijh+cli5SzPt/wnasXOlXyTVuKvxjDVdKLj77JUf26tjs+3INvdc398aZjAhwdHyysofFEhCNgSE7Uy0tqQXHheP3wfl5T05MN463x0F6JEsxax6lQ/xrM1goJR6ZV6cWZ5HctsWr0tWJ+N1K2LeZOdcs/P3Pj4fYFmKrf6Hf6T7y/nsg3a0flUDw1gfi9pGmOiyfkJM2Qe7Pkrg9gs3i0uC4TXlrGlzJ/O7j/VZN2n9RCRWjwlr7vvQuvhfmlgtkZ/2UgR4Lee5MKwJsk7CV7LWbqNOsKuS1il8PdFjODjR6qM9iMpckEbqYjhVk03XRkC9sSDNBpADGadIjbIQBYV6YE7QB6Ieinl1VR7jAhSXzAuNtH3aJDWD6dCEpBPvzcLyClIaxfEnptsP4wVQcgzvEsrJnSr+IZONRTiTMWQtObAhe1RylCqRLey+sGx9R3ElpipaRHZA2ZHFpfD5Vl3SKdO2LA8WJlw=
  - secure: AUbxmML9o2stM4UE0yfLvY/CbmBnjnmZdQhz9D7JX65mS7HhPPj56bvlucDAzd4c/BM3tElA/VWjawULQBA82E3z0UKKQ1qJUr89xa8aOw8LYefVjg/GnxnGf19qvV1eP6gII+hXOnG4TNUlD/AWqsNRODAFy8yHNtX0qJwTy14OmVjrjMjAPvw5czsk0QfS/P8CPq1ntZF7PpbAXH3Q4ns1dmFub9M0C81Hm/mYZWQKgYz3oG5kJPvNc2JH3LUlMD1fvnYrZGlM5QydgM1vlYaSV5ZjLyr/J3DR9GH4dqLco/NXgI1PD4y9gFFJ+DQHnppfW3DKOk5larpsB6OSgVOmYV08J9NT3tGr6oWZXqO7ACxg9Lyvaguch7Lx9ZmBCEw3gN0cFeDsSz1D6bLDl5ngflkDty9QLjD8bd8zBjuCh7nFGCb+MP5SVc/0fSTbJ/gvbxwoYzQN+hMupqMpPw5QT1Vy7FzPO8nX2WzKfoFMyGtQbJw1Yify7uRKWUFGHRoIZ/NEfR5+VHkyKufwibfx1lcH3uRCjT62aP8skkOzdw7qhDZ/PNGsigsGlCrcMsZBHJk5jJaRGfPZ1QSPr4YQtzhKlyyLPqQ2yqvunHsJyoAq4Xne87mh92f3/RG7k0cIlaUrGJvZ3BLGWHWYwINieeeBHwW0ZZ9w3CNgGqI=
  - secure: CyV4Mk53Z2vNNBcifXyh+g2qWMSlq52shS51/RgJcT2dy9tboTG11KqEHmfuKLQu9kjUjvMpoQywPa6cRlpbVP2wn+jqcY2+DDrDALPjXLsVqetn+b+R8gkFeRdvY3LQDN6uPWeLYt4Ku/xV+/K4KM7UJM2ODrNNFaYJTn1M8h/a3lIIq9gbJMzHYoDcRZGEyt507wLTylvCTpwLJEE/0UMxkIjbssGP1n5NF21U7e6qI2sj+/8ysjW1fSkMurWuq3Y0kH70BJqtjzjZvqUqbxbifwa+1Q5Q4Ekh1TUTDx6DgoSkWYGmZlaBY+Im3yB3SlWZymfsg9vftHXZcTRz8fiBZFr7Yz2zE2JmDwluN83SESHAWE9JCGgmTZn9mCoJ2Tu3WHnbAQpCDuWRoJOCBOA8eLcduFE8po3yCQNL3ig1Kc/Cu6eJjo7ySLpsktTDrRYDWA2ZO2449CNHFU6Fw5jNXt82ABIaz/zo+q3146Wo0oxIjFIQtBw5bQUuv0N5tnk5OeWFx1tPKqtqXnLPysqE79fp4em7wJcusZdJaK87tVlsqBvLmG7LHCEUp2/dwTownivQ6FUlROPryEyj6DQ6h0GYHARwtZPtFK/ws9YHk/vtxcrCpmwzICdRthcHPF3qOycJctFtGcekLv70aF+skPFUR6HwDRQB4L+yp2M=
